version: "3.9"
services:
  app:
    image: ${IMAGE}
    build:
      target: deploy
      context: ../
      dockerfile: environment/go/Dockerfile
    environment:
      ENV: DEV
      PORT: 8080
      DATABASE_URL: mh-api:P@ssw0rd@tcp(mh-api-dbsrv01)/mh-api?charset=utf8&parseTime=True&loc=Local
      ALLOW_URL: "*"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
