##########################
# secrets変数に設定すること
# - SERVICE_NAME
# - GCP_PROJECT_ID
# - GCP_REGION
# - GCP_REPOSITORY
# - GCP_SERVICE_ACCOUNT
#########################
name: Image Build and Push

on:
  push:

env:
  SERVICE_NAME: go-api
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-northeast1
  GCP_REPOSITORY: ${{ secrets.GCP_REPOSITORY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/go122-api:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build a docker image
        run: |
          cd environment
          IMAGE=${{ env.IMAGE }} docker compose build

      - name: Push the docker image
        run: docker push ${{ env.IMAGE }}

      - name: Checkout config repository
        uses: actions/checkout@v3
        with:
          repository: o-ga09/infra
          ref: main
          token: ${{ secrets.PAT }}
          path: infra
      
      - name: Update Image Tag
        id: update-image-tag
        working-directory: infra
        continue-on-error: true
        run: |
          yq -i '.spec.template.spec.containers[0].image = ${{ env.IMAGE }}' manifests/dev/api_20240206.yml
          git diff --name-only --exit-code

      - name: Commit and Push
        working-directory: infra
        if: steps.update-image-tag.outcome == 'failure'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit --author=. -m "Update Image Tag to"`printenv IMAGE_TAG`
          git push


