##########################
# secrets変数に設定すること
# - SERVICE_NAME
# - GCP_PROJECT_ID
# - GCP_REGION
# - GCP_REPOSITORY
# - GCP_SERVICE_ACCOUNT
#########################
name: Image Build and Push

on:
  push:
    branches:
      - "main"

env:
  SERVICE_NAME: go-api
  JOB_NAME: go-job
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-northeast1
  GCP_REPOSITORY: ${{ secrets.GCP_REPOSITORY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  API_IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/go122-api:${{ github.sha }}
  JOB_IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/go122-job:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build a docker image
        run: |
          docker build --platform linux/amd64 -t ${{ env.API_IMAGE }} --target deploy . -f environment/go/Dockerfile
          docker build --platform linux/amd64 -t ${{ env.JOB_IMAGE }} --target deploy-jobs . -f environment/go/Dockerfile

      - name: Push the docker image
        run: |
          docker push ${{ env.API_IMAGE }}
          docker push ${{ env.JOB_IMAGE }}

      - name: API Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.API_IMAGE }} \
            --project ${{ env.GCP_PROJECT_ID }} \
            --region ${{ env.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=${{ env.GCP_SERVICE_ACCOUNT }} \
            --quiet \
            --set-secrets=DATABASE_URL=DATABASE_URL:latest

      - name: Job Deploy to Cloud Run
        run: | 
          gcloud run jobs deploy ${{ env.JOB_NAME }} \
            --tasks 1 \
            --parallelism 1 \
            --max-retries 3 \
            --task-timeout 1m \
            --image ${{ env.JOB_IMAGE }} \
            --project ${{ env.GCP_PROJECT_ID }} \
            --region ${{ env.GCP_REGION }} \
            --service-account ${{ env.GCP_SERVICE_ACCOUNT }} \
            --set-secrets=DATABASE_URL=DATABASE_URL:latest
