##########################
# secrets変数に設定すること
# - SERVICE_NAME
# - GCP_PROJECT_ID
# - GCP_REGION
# - GCP_REPOSITORY
# - GCP_SERVICE_ACCOUNT
#########################
name: GCP Deploy

on:
  push:

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: asia-northeast1
  GCP_REPOSITORY: ${{ secrets.GCP_REPOSITORY }}
  GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
  IMAGE: asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/go122-api:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ env.GCP_SERVICE_ACCOUNT }}"

      - name: Configure docker for artifact registry
        run: |
          gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Build a docker image
        run: |
          cd environment
          IMAGE=${{ env.IMAGE }} docker compose build

      - name: Push the docker image
        run: docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE }} \
            --project ${{ env.GCP_PROJECT_ID }} \
            --region ${{ env.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated \
            --service-account=${{ env.GCP_SERVICE_ACCOUNT }} \
            --quiet
